version: "3"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: cloudsigma.com/php
        container_name: app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        networks:
            - my-story-network
        volumes:
            - ./:/var/www/html/
        depends_on:
            - db
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: always
        tty: true
        ports:
            - "8080:80"
            - "443:443"
        networks:
            - my-story-network

        volumes:
            - ./:/var/www/html/
            - ./docker/nginx:/etc/nginx/conf.d/
    db:
        image: mariadb:10.5
        container_name: db
        restart: always
        tty: true
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        networks:
            - my-story-network
        volumes:
            - dbdata:/var/lib/mysql

networks:
    my-story-network:
        driver: bridge
volumes:
    dbdata:
        driver: local